[features]
default = []
seeds = false

[programs.localnet]
certi_check = "11111111111111111111111111111111"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
