[features]
default = []
seeds = false

[programs.devnet]
certi_check = "BRVpnQ21mUX5Upy5krTN28cjMJdt8rQ4yAFssWMMZSQJ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
