[features]
default = []
seeds = false

[programs.devnet]
certi_check = "4aCWiNjpLPtMa1gQd3Tu5jfSpKEFDR3PbANP5br8Fmob"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "anchor test"
